from pydantic import BaseModel

from app.schemas.common import HealthResponse
from app.schemas.enums import (
    ActionPriority,
    Difficulty,
    EmotionLabel,
    ErrorCode,
    FinishStatus,
    InterviewMode,
    Language,
    NextAction,
    PracticeType,
    QuestionIntent,
    QuestionType,
    ScenarioCategory,
    SessionStatus,
    TranscriptSource,
)
from app.schemas.error import ErrorDetail, ErrorResponse
from app.schemas.evaluation import (
    AbilityDimensions,
    AbilityEvaluation,
    ActionItem,
    EvaluationReport,
    PsychologyDimensions,
    PsychologyEvaluation,
    ScoreItem,
    TurnFeedback,
)
from app.schemas.interview import (
    CandidateAnswer,
    CandidateProfile,
    FinishSessionResponse,
    InterviewQuestion,
    InterviewSession,
    InterviewTurn,
    SpeechMetrics,
    StartSessionRequest,
    StartSessionResponse,
    SubmitAnswerRequest,
    SubmitAnswerResponse,
)
from app.schemas.scenario import InterviewScenario, ScenariosResponse

CONTRACT_MODELS: list[type[BaseModel]] = [
    HealthResponse,
    InterviewScenario,
    ScenariosResponse,
    CandidateProfile,
    SpeechMetrics,
    CandidateAnswer,
    InterviewQuestion,
    InterviewSession,
    InterviewTurn,
    StartSessionRequest,
    StartSessionResponse,
    SubmitAnswerRequest,
    SubmitAnswerResponse,
    FinishSessionResponse,
    ScoreItem,
    AbilityDimensions,
    AbilityEvaluation,
    PsychologyDimensions,
    PsychologyEvaluation,
    TurnFeedback,
    ActionItem,
    EvaluationReport,
    ErrorDetail,
    ErrorResponse,
]

__all__ = [
    "ActionItem",
    "ActionPriority",
    "AbilityDimensions",
    "AbilityEvaluation",
    "CandidateAnswer",
    "CandidateProfile",
    "CONTRACT_MODELS",
    "Difficulty",
    "EmotionLabel",
    "ErrorCode",
    "ErrorDetail",
    "ErrorResponse",
    "EvaluationReport",
    "FinishSessionResponse",
    "FinishStatus",
    "HealthResponse",
    "InterviewMode",
    "InterviewQuestion",
    "InterviewScenario",
    "InterviewSession",
    "InterviewTurn",
    "Language",
    "NextAction",
    "PracticeType",
    "PsychologyDimensions",
    "PsychologyEvaluation",
    "QuestionIntent",
    "QuestionType",
    "ScenarioCategory",
    "ScenariosResponse",
    "ScoreItem",
    "SessionStatus",
    "SpeechMetrics",
    "StartSessionRequest",
    "StartSessionResponse",
    "SubmitAnswerRequest",
    "SubmitAnswerResponse",
    "TranscriptSource",
    "TurnFeedback",
]
